buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
		maven { url  = 'https://plugins.gradle.org/m2/' }
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
        classpath 'gradle.plugin.com.matthewprenger:CurseGradle:1.4.0'
        classpath "com.modrinth.minotaur:Minotaur:2.+"
    }
}

plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '5.1.+'
}

apply plugin: 'java'
apply plugin: 'com.matthewprenger.cursegradle'
apply plugin: "com.modrinth.minotaur"

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: 'official', version: '1.19.2'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'modernrecipes'

            mods {
                modernrecipes {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'modernrecipes'

            mods {
                modernrecipes {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'modernrecipes', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                modernrecipes {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        // location of the cursemaven
        url 'https://www.cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.19.2-43.4.2'
    runtimeOnly fg.deobf("curse.maven:applied-energistics-2-223794:${ae2_version}")
    runtimeOnly fg.deobf("curse.maven:aeinfinitybooster-559313:${aeinfinitybooster_version}")
    runtimeOnly fg.deobf("curse.maven:ad-astra-635042:${ad_astra_version}")
    runtimeOnly fg.deobf("curse.maven:aiot-botania-294815:${aiot_botania_version}")
    runtimeOnly fg.deobf("curse.maven:ato-405593:${alltheores_version}")
    runtimeOnly fg.deobf("curse.maven:apotheosis-313970:${apotheosis_version}")
    runtimeOnly fg.deobf("curse.maven:aquaculture-60028:${aquaculture_version}")
    runtimeOnly fg.deobf("curse.maven:ars_nouveau-401955:${ars_nouveau_version}")
    runtimeOnly fg.deobf("curse.maven:advanced-mining-dimension-332640:${advanced_mining_dimension_version}")
    runtimeOnly fg.deobf("curse.maven:bartering-station-666940:${bartering_station_version}")
    runtimeOnly fg.deobf("curse.maven:biomes-o-plenty-220318:${biomes_o_plenty_version}")
    runtimeOnly fg.deobf("curse.maven:blue-skies-312918:${blue_skies_version}")
    runtimeOnly fg.deobf("curse.maven:botania-225643:${botania_version}")
    runtimeOnly fg.deobf("curse.maven:botany-pots-tiers-526754:${botany_pots_tiers_version}")
    runtimeOnly fg.deobf("curse.maven:building-gadgets-298187:${building_gadgets_version}")
    runtimeOnly fg.deobf("curse.maven:charging-gadgets-399757:${charging_gadgets_version}")
    runtimeOnly fg.deobf("curse.maven:create-328085:${create_version}")
    runtimeOnly fg.deobf("curse.maven:createaddition-439890:${createaddition_version}")
    runtimeOnly fg.deobf("curse.maven:chipped-456956:${chipped_version}")
    runtimeOnly fg.deobf("curse.maven:cyclic-239286:${cyclic_version}")
    runtimeOnly fg.deobf("curse.maven:cc-tweaked-282001:${cc_tweaked_version}")
    runtimeOnly fg.deobf("curse.maven:construction-wand-399558:${construction_wand_version}")
    runtimeOnly fg.deobf("curse.maven:cooking-for-blockheads-231484:${cooking_for_blockheads_version}")
    runtimeOnly fg.deobf("curse.maven:chisels-bits-231095:${chisels_bits_version}")
    runtimeOnly fg.deobf("curse.maven:mcdoom-368765:${doom_version}")
    runtimeOnly fg.deobf("curse.maven:easy-mob-farm-563464:${easy_mob_farm_version}")
    runtimeOnly fg.deobf("curse.maven:eidolon-repraised-870250:${eidolon_repraised_version}")
    runtimeOnly fg.deobf("curse.maven:enchanting-infuser-forge-551151:${enchanting_infuser_version}")
    runtimeOnly fg.deobf("curse.maven:experience-obelisk-579484:${experience_obelisk_version}")
    runtimeOnly fg.deobf("curse.maven:environmental-388992:${environmental_version}")
    runtimeOnly fg.deobf("curse.maven:enigmatic-legacy-336184:${enigmatic_legacy_version}")
    runtimeOnly fg.deobf("curse.maven:energymeter-532169:${energymeter_version}")
    runtimeOnly fg.deobf("curse.maven:explorers-compass-491794:${explorers_compass_version}")
    runtimeOnly fg.deobf("curse.maven:extended-crafting-268387:${extended_crafting_version}")
    runtimeOnly fg.deobf("curse.maven:extended-mushrooms-365507:${extended_mushrooms_version}")
    runtimeOnly fg.deobf("curse.maven:extra-disks-351491:${extra_disks_version}")
    runtimeOnly fg.deobf("curse.maven:extrastorage-410168:${extrastorage_version}")
    runtimeOnly fg.deobf("curse.maven:extreme-reactors-250277:${extreme_reactors_version}")
    runtimeOnly fg.deobf("curse.maven:enderchests-363535:${enderchests_version}")
    runtimeOnly fg.deobf("curse.maven:fancy-battleaxe-258152:${fancy_battleaxe_version}")
    runtimeOnly fg.deobf("curse.maven:flux-networks-248020:${flux_networks_version}")
    runtimeOnly fg.deobf("curse.maven:forbidden-arcanus-309858:${forbidden_arcanus_version}")
    runtimeOnly fg.deobf("curse.maven:forcecraft-454802:${forcecraft_version}")
    runtimeOnly fg.deobf("curse.maven:framedblocks-441647:${framedblocks_version}")
    runtimeOnly fg.deobf("curse.maven:glassential-319194:${glassential_version}")
    runtimeOnly fg.deobf("curse.maven:gobber-301700:${gobber_version}")
    runtimeOnly fg.deobf("curse.maven:greater-eye-of-ender-forge-374520:${greater_eye_of_ender_version}")
    runtimeOnly fg.deobf("curse.maven:immersive-engineering-231951:${immersive_engineering_version}")
    runtimeOnly fg.deobf("curse.maven:industrial-foregoing-266515:${industrial_foregoing_version}")
    runtimeOnly fg.deobf("curse.maven:inventory-pets-229380:${inventory_pets_version}")
    runtimeOnly fg.deobf("curse.maven:iron-bows-forge-631414:${iron_bows_forge_version}")
    runtimeOnly fg.deobf("curse.maven:iron-chests-228756:${iron_chests_version}")
    runtimeOnly fg.deobf("curse.maven:iron-coals-401945:${iron_coals_version}")
    runtimeOnly fg.deobf("curse.maven:iron-furnaces-237664:${iron_furnaces_version}")
    runtimeOnly fg.deobf("curse.maven:iron-jetpacks-284497:${iron_jetpacks_version}")
    runtimeOnly fg.deobf("curse.maven:little-logistics-570050:${little_logistics_version}")
    runtimeOnly fg.deobf("curse.maven:material-elements-541620:${material_elements_version}")
    runtimeOnly fg.deobf("curse.maven:mekanism-268560:${mekanism_version}")
    runtimeOnly fg.deobf("curse.maven:mekanism-generators-268566:${mekanism_generators_version}")
    runtimeOnly fg.deobf("curse.maven:mining-gadgets-351748:${mining_gadgets_version}")
    runtimeOnly fg.deobf("curse.maven:modular-routers-250294:${modular_routers_version}")
    runtimeOnly fg.deobf("curse.maven:monster-plus-676418:${monster_plus_version}")
    runtimeOnly fg.deobf("curse.maven:mutant-monsters-852665:${mutant_monsters_version}")
    runtimeOnly fg.deobf("curse.maven:mystical-agriculture-246640:${mystical_agriculture_version}")
    runtimeOnly fg.deobf("curse.maven:mystical-agradditions-256247:${mystical_agradditions_version}")
    runtimeOnly fg.deobf("curse.maven:mythicbotany-400058:${mythicbotany_version}")
    runtimeOnly fg.deobf("curse.maven:measurements-478559:${measurements_version}")
    runtimeOnly fg.deobf("curse.maven:natures-aura-306626:${naturesaura_version}")
    runtimeOnly fg.deobf("curse.maven:natures-compass-252848:${natures_compass_version}")
    runtimeOnly fg.deobf("curse.maven:nethers-delight-496394:${nethers_delight_version}")
    runtimeOnly fg.deobf("curse.maven:not-enough-wands-235595:${not_enough_wands_version}")
    runtimeOnly fg.deobf("curse.maven:occultism-361026:${occultism_version}")
    runtimeOnly fg.deobf("curse.maven:pipez-443900:${pipez_version}")
    runtimeOnly fg.deobf("curse.maven:prefab-246550:${prefab_version}")
    runtimeOnly fg.deobf("curse.maven:psi_version-241665:${psi_version}")
    runtimeOnly fg.deobf("curse.maven:pneumaticcraft-repressurized-281849:${pneumaticcraft_repressurizedz_version}")
    runtimeOnly fg.deobf("curse.maven:quark-243121:${quark_version}")
    runtimeOnly fg.deobf("curse.maven:ranged-pumps-247496:${ranged_pumps_version}")
    runtimeOnly fg.deobf("curse.maven:rebornstorage-256662:${rebornstorage_version}")
    runtimeOnly fg.deobf("curse.maven:rebornstorage-256662:${rebornstorage_version}")
    runtimeOnly fg.deobf("curse.maven:refined-storage-243076:${refinedstorage_version}")
    runtimeOnly fg.deobf("curse.maven:reliquary-reincarnations-241319:${reliquary_reincarnations_version}")
    runtimeOnly fg.deobf("curse.maven:rftools-base-326041:${rftools_base_version}")
    runtimeOnly fg.deobf("curse.maven:rftools-control-250763:${rftools_control_version}")
    runtimeOnly fg.deobf("curse.maven:rftools-control-350006:${rftools_storage_version}")
    runtimeOnly fg.deobf("curse.maven:rftools-control-347706:${rftools_builder_version}")
    runtimeOnly fg.deobf("curse.maven:rftools-utility-342466:${rftools_utility_version}")
    runtimeOnly fg.deobf("curse.maven:scannable-266784:${scannable_version}")
    runtimeOnly fg.deobf("curse.maven:security-craft-64760:${security_craft_version}")
    runtimeOnly fg.deobf("curse.maven:shrink-426386:${shrink_version}")
    runtimeOnly fg.deobf("curse.maven:sophisticated-backpacks-422301:${sophisticated_backpacks_version}")
    runtimeOnly fg.deobf("curse.maven:sophisticated-storage-619320:${sophisticated_storage_version}")
    runtimeOnly fg.deobf("curse.maven:creeperhost-presents-steves-carts-551524:${creeperhost_presents_steves_carts_version}")
    runtimeOnly fg.deobf("curse.maven:storage-racks-551524:${storage_racks_version}")
    runtimeOnly fg.deobf("curse.maven:structure-compass-319598:${structure_compass_version}")
    runtimeOnly fg.deobf("curse.maven:tinkers-construct-74072:${tinkers_construct_version}")
    runtimeOnly fg.deobf("curse.maven:time-in-a-bottle-standalone-445025:${tiab_version}")
    runtimeOnly fg.deobf("curse.maven:tool-belt-260262:${tool_belt_version}")
    runtimeOnly fg.deobf("curse.maven:torchmaster-254268:${torchmaster_version}")
    runtimeOnly fg.deobf("curse.maven:trading-post-254268:${trading_post_version}")
    runtimeOnly fg.deobf("curse.maven:the-twilight-forest-227639:${tf_version}")
    runtimeOnly fg.deobf("curse.maven:viescraft-airships-246795:${viescraft_airships_version}")
    runtimeOnly fg.deobf("curse.maven:lets-do-vinery-704465:${lets_do_vinery_version}")
    runtimeOnly fg.deobf("curse.maven:waystones-245755:${waystones_version}")
    runtimeOnly fg.deobf("curse.maven:wireless-chargers-510656:${wireless_chargers_version}")
    runtimeOnly fg.deobf("curse.maven:wormhole-portals-396803:${wormhole_portals_version}")
    runtimeOnly fg.deobf("curse.maven:xnet-260912:${xnet_version}")
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "modernrecipes",
                "Specification-Vendor"    : "AzureDoom",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "AzureDoom",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

if (file('key.properties').exists()) {
    curseforge {
        def curseProp = new Properties()
        File secretPropsFile = file("key.properties")
        curseProp.load(secretPropsFile.newInputStream())

        project {
            apiKey = curseProp.getProperty('curseKey')
            id = "863339" 
            releaseType = "release"
            changelogType = 'text'
            changelog = file('changelog.txt')
            addGameVersion("1.19.2")
            addGameVersion("Forge")
            addGameVersion("Java 17")
        }
    }
}

if (file('key.properties').exists()) {
	modrinth {
		def modrinthProp = new Properties()
		File secretPropsFile = file("key.properties")
		modrinthProp.load(secretPropsFile.newInputStream())
		
		token = modrinthProp.getProperty('modrinthKey')
		projectId = 'Ty4peQTy' 
		versionNumber = project.mod_version 
		versionName = 'Forge 1.19.2'
		uploadFile = jar 
		changelog = rootProject.file("changelog.txt").text
		gameVersions = ['1.19.2']
		loaders = ['forge']
	}
}
