# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21
parchment_mappings_version=2024.06.23
minecraft_version=1.21
minecraft_version_range=[1.21,1.21.1)
neo_version=21.0.37-beta
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

## Mod Properties
archives_base_name=modernrecipes-1.21
curseforge_id=863339
curseforge_slug=moderns-monumental-recipe
modrinth_id=Ty4peQTy
mod_id=modernrecipes
mod_name=Modern's Monumental Recipe
mod_license=All Rights Reserved
mod_version=0.1
mod_group_id=com.azure.modernrecipes
mod_authors=AzureDoom, ModernGamingWorld
mod_description=This mod is the Core Mod used for all the Custom Recipes in Monumental Experience 