org.gradle.daemon=false
mod_version=0.110
archives_base_name=modernrecipes-1.19.2
maven_group=com.azuredoom.modernrecipes


ae2_version = 5014801
aeinfinitybooster_version = 3940200
ad_astra_version = 4643668
aiot_botania_version = 4978183
alltheores_version = 4046926
apotheosis_version = 5322410
aquaculture_version = 5320128
ars_nouveau_version = 5171729
advanced_mining_dimension_version = 4973553
bartering_station_version = 4067998
biomes_o_plenty_version = 4473556
blue_skies_version = 3966273
botania_version = 4557912
botany_pots_tiers_version = 4461120
building_gadgets_version = 5358157
charging_gadgets_version = 3955867
chipped_version = 4558849
chisels_bits_version = 5065808
cc_tweaked_version = 5005332
construction_wand_version = 4455719
cooking_for_blockheads_version = 4942589
create_version = 4835190
createaddition_version = 5099757
cyclic_version = 4660268
doom_version = 4715005
easy_mob_farm_version = 5138919
eidolon_repraised_version = 5058501
enchanting_infuser_version = 4041213
experience_obelisk_version = 5476385
environmental_version = 5292368
enigmatic_legacy_version = 4392950
energymeter_version = 4032160
explorers_compass_version = 4016467
extended_crafting_version = 4991289
extended_mushrooms_version = 5368739
extra_disks_version = 4978179
extrastorage_version = 4031259
extreme_reactors_version = 4715935
enderchests_version = 4859148
fancy_battleaxe_version = 3851440
flux_networks_version = 4620438
forbidden_arcanus_version = 4852521
forcecraft_version = 5105633
framedblocks_version = 4762544
glassential_version = 3901780
gobber_version = 5329816
greater_eye_of_ender_version = 4000630
immersive_engineering_version = 5222176
industrial_foregoing_version = 5338563
inventory_pets_version = 5414263
iron_bows_forge_version = 4681090
iron_chests_version = 3966365
iron_coals_version = 3971341
iron_furnaces_version = 4366408
iron_jetpacks_version = 5050857
little_logistics_version = 4563179
material_elements_version = 4276976
mekanism_version = 4644795
mekanism_generators_version = 4644798
mining_gadgets_version = 4733515
modular_routers_version = 4695682
monster_plus_version = 4496903
mutant_monsters_version = 4569847
mystical_agriculture_version = 5225677
mystical_agradditions_version = 5503117
mythicbotany_version = 4546050
measurements_version = 4371566
naturesaura_version = 4613484
natures_compass_version = 4118390
nethers_delight_version = 4731072
not_enough_wands_version = 4462367
occultism_version = 5137571
pipez_version = 5478837
pneumaticcraft_repressurizedz_version = 5280236
prefab_version = 4187306
psi_version = 4952168
quark_version = 4812006
ranged_pumps_version = 4012692
rebornstorage_version = 4376288
refinedstorage_version = 4861827
rechiseled_version = 5286283
reliquary_reincarnations_version = 4666081
rftools_base_version = 5443280
rftools_control_version = 5294706
rftools_storage_version = 5294704
rftools_builder_version = 5294701
rftools_utility_version = 5294697
scannable_version = 4284889
security_craft_version = 4531283
shrink_version = 4407257
sophisticated_backpacks_version = 5194759
sophisticated_storage_version = 5194750
creeperhost_presents_steves_carts_version = 4543471
storage_racks_version = 4543471
structure_compass_version = 5369380
tinkers_construct_version = 5358052
tiab_version = 3879896
tool_belt_version = 4124032
torchmaster_version = 4669791
trading_post_version = 4669791
tf_version = 4389567
viescraft_airships_version = 4015230
lets_do_vinery_version = 4833017
waystones_version = 4943265
wireless_chargers_version = 5294254
wormhole_portals_version = 5301749
xnet_version = 5443285