org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.20.3
neogradle.subsystems.parchment.mappingsVersion=2023.12.31
minecraft_version=1.20.4
minecraft_version_range=[1.20.4,1.21)
neo_version=20.4.225
neo_version_range=[20.4,)
loader_version_range=[2,)
archives_base_name=modernrecipes-1.20.4
curseforge_id=863339
curseforge_slug=moderns-monumental-recipe
modrinth_id=Ty4peQTy

## Mod Properties
mod_id=modernrecipes
mod_name=Modern's Monumental Recipe
mod_license=All Rights Reserved
mod_version=0.1
mod_group_id=com.azure.modernrecipes
mod_authors=AzureDoom, ModernGamingWorld
mod_description=This mod is the Core Mod used for all the Custom Recipes in Monumental Experience 