modLoader="javafml" 
loaderVersion="[47,)"
license="All rights reserved"
[[mods]] 
modId="modernrecipes" 
version="${file.jarVersion}" 
displayName="Modern's Monumental Recipe" 
logoFile="logo.png" 
description='''
This mod is the Core Mod used for all the Custom Recipes in Monumental Experience 
'''
[[dependencies.modernrecipes]]
    modId="forge" 
    mandatory=true 
    versionRange="[47,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.modernrecipes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
