modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"
    [[dependencies.${mod_id}]]
    modId="ae2"
    type="required"
    versionRange="${ae2_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="aquaculture"
    type="required"
    versionRange="${aquaculture_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="biomesoplenty"
    type="required"
    versionRange="${biomesoplenty_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="the_bumblezone"
    type="required"
    versionRange="${the_bumblezone_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="explorerscompass"
    type="required"
    versionRange="${explorers_compass_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="naturescompass"
    type="required"
    versionRange="${natures_compass_version}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="structurecompass"
    type="required"
    versionRange="${structure_compass_version}"
    ordering="AFTER"
    side="BOTH"